---
user_name: cwalsh
user_group: cwalsh

hostname: shallowblue

dotfiles_url: 
dotfiles_destination:

aur:
    dir: aur
    packages:
        - aura-bin
        - downgrade
        - overdue
        - zplug
        - dateutils
        - miller
        - myrepos

ssh:
    port: 22
    user_key: /root/id_rsa
    enable_sshd: False

gnupg:
    enable_agent: True
    emulate_ssh: True

mail:
    sync_tool: isync
    sync_pim: True
    sync_taskwarrior: True
    sync_time: 5min
    sync_boot_delay: 2min
    sync_on: trusted

video_drivers:
    - libva-intel-driver

filesystem_packages:
    - dosfstools
    - ntfs-3g
    - exfat-utils

browser_choices:
    - firefox -P default
    - firefox -P work
    - firewarden chromium
    - tor-browser-en
    - play
    - qcode

tarsnapper:
  deltas: 1h 1d 7d 30d 365d
  timer:
    schedule: daily
    run_on: trusted

gitannex:
    stop_on_untrusted: True

bitlbee:
    run_on: trusted
    torify: True

bootloader: grub

postgresql:
    enable: True

fingerprint: False

tor:
    run_on: trusted

localtime:
    run_on: trusted

nameservers:
    - 8.8.8.8       # Google
    - 209.244.0.3   # Level 3
    - 74.82.42.42   # Hurricane Electric

bluetooth:
    disable: False

firejail:
    blacklist:
        - ~/.calendars
        - ~/.config/vdirsyncer
        - ~/.contacts
        - ~/.keys
        - ~/.mbsyncrc
        - ~/.offlineimap
        - ~/.offlineimaprc
        - ~/.password-store
        - ~/.vdirsyncer
        - ~/library/ledger

cryptshot:
    - name: alta
      uuid: 0a0db776-84c5-48e1-9079-cacfbc5de8a3
      keyfile: /home/pigmonkey/.keys/usb-alta.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3
    - name: bishorn
      uuid: baeb40a2-b19e-4adc-8ef6-44ee720a4d1a
      keyfile: /home/pigmonkey/.keys/usb-bishorn.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3
    - name: pilchuck
      uuid: d96a0fc3-7ea1-42f7-b0d0-42e573c478bd
      keyfile: /home/pigmonkey/.keys/usb-pilchuck.key
      retain:
        - level: daily
          interval: 7
        - level: weekly
          interval: 6
        - level: monthly
          interval: 3

hostsctl:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

himawaripy:
    run_time: 15min
    run_boot_delay: 2min
    run_on: trusted
    flags: --auto-offset --level 4
