---
- name: Install GNU-Stow
  pacman:
    name: stow
    state: present

- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    update: no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: rcup -d /home/{{ user.name }}/{{ dotfiles.destination }} {{ dotfiles.rcup_flags }}
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
