---
- name: Install bspwm
  pacman:
    name: bspwm
    state: present
  tags:
    - bspwm

- name: Install sxhkd
  pacman:
    name: sxhkd
    state: present
  tags:
    - sxhkd

- name: Install dmenu
  pacman:
    name: dmenu
    state: present
  tags:
    - dmenu

- name: Install feh
  pacman:
    name: feh
    state: present
  tags:
    - feh

- include: example.yml
  when: bspwm_example is defined and bspwm_example
