---
- name: Install Xorg
  pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  pacman:
    name: xorg-xev
    state: present

- name: Install video driver(s)
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ video_drivers }}"

- name: Add user to video group
  user:
    name: "{{ user_name }}"
    groups: video
    append: yes

- name: Create default xinitrc
  copy:
    src: /etc/X11/xinit/xinitrc
    dest: /home/{{ user_name }}/.xinitrc
    remote_src: True
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  tags:
    - example

- name: Install xorg example packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-twm
    - xorg-xclock
    - xterm
  tags:
    - example
    

- include: unclutter.yml
  #- include: autorandr.yml
  #- include: srandrd.yml
- include: termite.yml
- include: autocutsel.yml
- include: xdg.yml
