---
- name: Install NetworkManager and dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - networkmanager
      - networkmanager-openvpn
      - gnome-keyring
      - dhclient

- name: Copy the NetworkManager config to specify dhclient
  template:
    src: NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf
    mode: 644

- name: Stop/Disable dhcpcd if it was being used
  service:
    name: dhcpcd.service
    enabled: False
    state: stopped

- name: Enable and start NetworkManager
  service:
    name: NetworkManager.service
    enabled: True
    state: started

- name: Enable and start NetworkManager dispatcher
  service:
    name: NetworkManager-dispatcher.service
    enabled: True
    state: started
