---
- include: beets.yml
- include: imagemagick.yml
- include: inkscape.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: mcomix.yml
- include: flac2all.yml
- include: qcode.yml

- name: Install misc media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - gst-libav
    - gst-plugins-good
    - exiv2
    - perl-image-exiftool
    - opus-tools

- name: Install youtube-dl
  pacman: name=youtube-dl state=present
